version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - app-network

  users-service:
    build:
      context: .
      dockerfile: ./apps/users-service/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - kafka

  task-api-gateway:
    build:
      context: .
      dockerfile: ./apps/task-api-gateway/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - users-service

  notification-service:
    build:
      context: .
      dockerfile: ./apps/notification-service/Dockerfile
    ports:
      - "3002:3000"
    networks:
      - app-network
    depends_on:
      - kafka

networks:
  app-network:
    driver: bridge